name: mrz_scanner
description: A package that allows you to Scan any kind of documents that have any mrz format
version: 0.0.2+2
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  camerawesome: ^2.1.0
  google_mlkit_text_recognition: ^0.14.0
  mrz_parser: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
