name: mrz_scanner
description: A package that allows you to Scan any kind of documents that have any mrz format
version: 1.0.0+4
homepage: https://github.com/F-BONAPARTA/mrz_scanner

environment:
  sdk: '>=2.18.1 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.12.0
  flutter_tesseract_ocr: ^0.4.30
  path_provider: ^2.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/tessdata_config.json
    - assets/tessdata/